plugins {
	id 'com.unascribed.nilgradle' version '1.3.5'
}

sourceCompatibility = 8
targetCompatibility = 8

group = 'com.unascribed'
archivesBaseName = 'UpsilonFixes'
version = '1.3.1'

repositories {
	mavenCentral {
		content {
			includeGroup 'org.lwjgl.lwjgl'
		}
	}
	maven {
		url 'https://repo.sleeping.town'
		content {
			includeGroup 'com.unascribed'
		}
	}
	maven {
		url 'https://maven.minecraftforge.net'
		metadataSources {
			artifact()
		}
		content {
			includeGroup 'net.minecraftforge'
		}
	}
	mavenLocal()
	flatDir {
		dirs 'libs'
		content {
			includeGroup 'libs'
		}
	}
}

nil {
	id "upsilonfixes"
	standalone false
}

dependencies {
	loader 'com.unascribed:nilloader:1.3.1'

	implementation('org.lwjgl.lwjgl:lwjgl:2.9.3') {
		transitive = false
	}

	game nil.minecraft('1.4.7', 'client')
	mod 'net.minecraftforge:forge:1.4.7-6.6.2.534:universal@zip'
	mod 'libs:IC2'
	mod 'libs:RedPowerCore'
	mod 'libs:RedPowerDigital'
	mod 'libs:RedPowerMechanical'
	mod 'libs:ChiselRetro'
	mod 'libs:GregTech'
	mod 'libs:LogisticsPipes'
	mod 'libs:XyCraft'
	mod 'libs:ThermalExpansion'
	mod 'libs:BuildCraft'
	mod 'libs:DartCraft'
}

mappings {
	work nil.mcpArchive('1.4.7', '726a')
}
