plugins {
	id 'com.unascribed.nilgradle' version '1.1'
}

sourceCompatibility = 8
targetCompatibility = 8

group = 'com.unascribed'
archivesBaseName = 'UpsilonFixes'
version = '1.0'

repositories {
	maven {
		url 'https://repo.sleeping.town'
		content {
			includeGroup 'com.unascribed'
		}
	}
	maven {
		url 'https://maven.minecraftforge.net'
		metadataSources {
			artifact()
		}
		content {
			includeGroup 'net.minecraftforge'
		}
	}
}

nil {
	id "upsilonfixes"
	standalone false
}

dependencies {
	loader 'com.unascribed:nilloader:1.0'

	game nil.minecraft('1.4.7', 'client')
	mod 'net.minecraftforge:forge:1.4.7-6.6.2.534:universal@zip'
}

mappings {
	work nil.mcpArchive('1.4.7', '726a')
}
